using CommunityToolkit.Mvvm.ComponentModel;
using System.Windows;

namespace Projekt524.ViewModel;

public partial class ViewModel
{
    [ObservableProperty] private string? _stringVornameAnzahl00;
    [ObservableProperty] private string? _stringVornameAnzahl01;
    [ObservableProperty] private string? _stringVornameAnzahl02;
    [ObservableProperty] private string? _stringVornameAnzahl03;
    [ObservableProperty] private string? _stringVornameAnzahl04;
    [ObservableProperty] private string? _stringVornameAnzahl05;
    [ObservableProperty] private string? _stringVornameAnzahl06;
    [ObservableProperty] private string? _stringVornameAnzahl07;
    [ObservableProperty] private string? _stringVornameAnzahl08;
    [ObservableProperty] private string? _stringVornameAnzahl09;
    [ObservableProperty] private string? _stringVornameAnzahl10;
    [ObservableProperty] private string? _stringVornameAnzahl11;
    [ObservableProperty] private string? _stringVornameAnzahl12;
    [ObservableProperty] private string? _stringVornameAnzahl13;
    [ObservableProperty] private string? _stringVornameAnzahl14;
    [ObservableProperty] private string? _stringVornameAnzahl15;
    [ObservableProperty] private string? _stringVornameAnzahl16;
    [ObservableProperty] private string? _stringVornameAnzahl17;
    [ObservableProperty] private string? _stringVornameAnzahl18;
    [ObservableProperty] private string? _stringVornameAnzahl19;

    [ObservableProperty] private string? _stringVornameSelbstlaut00;
    [ObservableProperty] private string? _stringVornameSelbstlaut01;
    [ObservableProperty] private string? _stringVornameSelbstlaut02;
    [ObservableProperty] private string? _stringVornameSelbstlaut03;
    [ObservableProperty] private string? _stringVornameSelbstlaut04;
    [ObservableProperty] private string? _stringVornameSelbstlaut05;
    [ObservableProperty] private string? _stringVornameSelbstlaut06;
    [ObservableProperty] private string? _stringVornameSelbstlaut07;
    [ObservableProperty] private string? _stringVornameSelbstlaut08;
    [ObservableProperty] private string? _stringVornameSelbstlaut09;
    [ObservableProperty] private string? _stringVornameSelbstlaut10;
    [ObservableProperty] private string? _stringVornameSelbstlaut11;
    [ObservableProperty] private string? _stringVornameSelbstlaut12;
    [ObservableProperty] private string? _stringVornameSelbstlaut13;
    [ObservableProperty] private string? _stringVornameSelbstlaut14;
    [ObservableProperty] private string? _stringVornameSelbstlaut15;
    [ObservableProperty] private string? _stringVornameSelbstlaut16;
    [ObservableProperty] private string? _stringVornameSelbstlaut17;
    [ObservableProperty] private string? _stringVornameSelbstlaut18;
    [ObservableProperty] private string? _stringVornameSelbstlaut19;

    [ObservableProperty] private string? _stringVornameMitlaut00;
    [ObservableProperty] private string? _stringVornameMitlaut01;
    [ObservableProperty] private string? _stringVornameMitlaut02;
    [ObservableProperty] private string? _stringVornameMitlaut03;
    [ObservableProperty] private string? _stringVornameMitlaut04;
    [ObservableProperty] private string? _stringVornameMitlaut05;
    [ObservableProperty] private string? _stringVornameMitlaut06;
    [ObservableProperty] private string? _stringVornameMitlaut07;
    [ObservableProperty] private string? _stringVornameMitlaut08;
    [ObservableProperty] private string? _stringVornameMitlaut09;
    [ObservableProperty] private string? _stringVornameMitlaut10;
    [ObservableProperty] private string? _stringVornameMitlaut11;
    [ObservableProperty] private string? _stringVornameMitlaut12;
    [ObservableProperty] private string? _stringVornameMitlaut13;
    [ObservableProperty] private string? _stringVornameMitlaut14;
    [ObservableProperty] private string? _stringVornameMitlaut15;
    [ObservableProperty] private string? _stringVornameMitlaut16;
    [ObservableProperty] private string? _stringVornameMitlaut17;
    [ObservableProperty] private string? _stringVornameMitlaut18;
    [ObservableProperty] private string? _stringVornameMitlaut19;


    [ObservableProperty] private string? _stringNachnameAnzahl00;
    [ObservableProperty] private string? _stringNachnameAnzahl01;
    [ObservableProperty] private string? _stringNachnameAnzahl02;
    [ObservableProperty] private string? _stringNachnameAnzahl03;
    [ObservableProperty] private string? _stringNachnameAnzahl04;
    [ObservableProperty] private string? _stringNachnameAnzahl05;
    [ObservableProperty] private string? _stringNachnameAnzahl06;
    [ObservableProperty] private string? _stringNachnameAnzahl07;
    [ObservableProperty] private string? _stringNachnameAnzahl08;
    [ObservableProperty] private string? _stringNachnameAnzahl09;
    [ObservableProperty] private string? _stringNachnameAnzahl10;
    [ObservableProperty] private string? _stringNachnameAnzahl11;
    [ObservableProperty] private string? _stringNachnameAnzahl12;
    [ObservableProperty] private string? _stringNachnameAnzahl13;
    [ObservableProperty] private string? _stringNachnameAnzahl14;
    [ObservableProperty] private string? _stringNachnameAnzahl15;
    [ObservableProperty] private string? _stringNachnameAnzahl16;
    [ObservableProperty] private string? _stringNachnameAnzahl17;
    [ObservableProperty] private string? _stringNachnameAnzahl18;
    [ObservableProperty] private string? _stringNachnameAnzahl19;

    [ObservableProperty] private string? _stringNachnameSelbstlaut00;
    [ObservableProperty] private string? _stringNachnameSelbstlaut01;
    [ObservableProperty] private string? _stringNachnameSelbstlaut02;
    [ObservableProperty] private string? _stringNachnameSelbstlaut03;
    [ObservableProperty] private string? _stringNachnameSelbstlaut04;
    [ObservableProperty] private string? _stringNachnameSelbstlaut05;
    [ObservableProperty] private string? _stringNachnameSelbstlaut06;
    [ObservableProperty] private string? _stringNachnameSelbstlaut07;
    [ObservableProperty] private string? _stringNachnameSelbstlaut08;
    [ObservableProperty] private string? _stringNachnameSelbstlaut09;
    [ObservableProperty] private string? _stringNachnameSelbstlaut10;
    [ObservableProperty] private string? _stringNachnameSelbstlaut11;
    [ObservableProperty] private string? _stringNachnameSelbstlaut12;
    [ObservableProperty] private string? _stringNachnameSelbstlaut13;
    [ObservableProperty] private string? _stringNachnameSelbstlaut14;
    [ObservableProperty] private string? _stringNachnameSelbstlaut15;
    [ObservableProperty] private string? _stringNachnameSelbstlaut16;
    [ObservableProperty] private string? _stringNachnameSelbstlaut17;
    [ObservableProperty] private string? _stringNachnameSelbstlaut18;
    [ObservableProperty] private string? _stringNachnameSelbstlaut19;

    [ObservableProperty] private string? _stringNachnameMitlaut00;
    [ObservableProperty] private string? _stringNachnameMitlaut01;
    [ObservableProperty] private string? _stringNachnameMitlaut02;
    [ObservableProperty] private string? _stringNachnameMitlaut03;
    [ObservableProperty] private string? _stringNachnameMitlaut04;
    [ObservableProperty] private string? _stringNachnameMitlaut05;
    [ObservableProperty] private string? _stringNachnameMitlaut06;
    [ObservableProperty] private string? _stringNachnameMitlaut07;
    [ObservableProperty] private string? _stringNachnameMitlaut08;
    [ObservableProperty] private string? _stringNachnameMitlaut09;
    [ObservableProperty] private string? _stringNachnameMitlaut10;
    [ObservableProperty] private string? _stringNachnameMitlaut11;
    [ObservableProperty] private string? _stringNachnameMitlaut12;
    [ObservableProperty] private string? _stringNachnameMitlaut13;
    [ObservableProperty] private string? _stringNachnameMitlaut14;
    [ObservableProperty] private string? _stringNachnameMitlaut15;
    [ObservableProperty] private string? _stringNachnameMitlaut16;
    [ObservableProperty] private string? _stringNachnameMitlaut17;
    [ObservableProperty] private string? _stringNachnameMitlaut18;
    [ObservableProperty] private string? _stringNachnameMitlaut19;

    [ObservableProperty] private string? _stringGeburtstag00;
    [ObservableProperty] private string? _stringGeburtstag01;
    [ObservableProperty] private string? _stringGeburtstag02;
    [ObservableProperty] private string? _stringGeburtstag03;
    [ObservableProperty] private string? _stringGeburtstag04;
    [ObservableProperty] private string? _stringGeburtstag05;
    [ObservableProperty] private string? _stringGeburtstag06;
    [ObservableProperty] private string? _stringGeburtstag07;
    [ObservableProperty] private string? _stringGeburtstag08;
    [ObservableProperty] private string? _stringGeburtstag09;
    [ObservableProperty] private string? _stringGeburtstag10;
    [ObservableProperty] private string? _stringGeburtstag11;
    [ObservableProperty] private string? _stringGeburtstag12;
    [ObservableProperty] private string? _stringGeburtstag13;
    [ObservableProperty] private string? _stringGeburtstag14;
    [ObservableProperty] private string? _stringGeburtstag15;
    [ObservableProperty] private string? _stringGeburtstag16;
    [ObservableProperty] private string? _stringGeburtstag17;
    [ObservableProperty] private string? _stringGeburtstag18;
    [ObservableProperty] private string? _stringGeburtstag19;

    [ObservableProperty] private string? _stringMontag;
    [ObservableProperty] private string? _stringDienstag;
    [ObservableProperty] private string? _stringMittwoch;
    [ObservableProperty] private string? _stringDonnerstag;
    [ObservableProperty] private string? _stringFreitag;
    [ObservableProperty] private string? _stringSamstag;
    [ObservableProperty] private string? _stringSonntag;
    [ObservableProperty] private string? _stringWochentageSumme;

    [ObservableProperty] private string? _stringJaenner;
    [ObservableProperty] private string? _stringFebruar;
    [ObservableProperty] private string? _stringMaerz;
    [ObservableProperty] private string? _stringApril;
    [ObservableProperty] private string? _stringMai;
    [ObservableProperty] private string? _stringJuni;
    [ObservableProperty] private string? _stringJuli;
    [ObservableProperty] private string? _stringAugust;
    [ObservableProperty] private string? _stringSeptember;
    [ObservableProperty] private string? _stringOktober;
    [ObservableProperty] private string? _stringNovember;
    [ObservableProperty] private string? _stringDezember;
    [ObservableProperty] private string? _stringMonateSumme;


    [ObservableProperty] private Thickness? _thicknessMontag;
    [ObservableProperty] private Thickness? _thicknessDienstag;
    [ObservableProperty] private Thickness? _thicknessMittwoch;
    [ObservableProperty] private Thickness? _thicknessDonnerstag;
    [ObservableProperty] private Thickness? _thicknessFreitag;
    [ObservableProperty] private Thickness? _thicknessSamstag;
    [ObservableProperty] private Thickness? _thicknessSonntag;

    [ObservableProperty] private Thickness? _thicknessJaenner;
    [ObservableProperty] private Thickness? _thicknessFebruar;
    [ObservableProperty] private Thickness? _thicknessMaerz;
    [ObservableProperty] private Thickness? _thicknessApril;
    [ObservableProperty] private Thickness? _thicknessMai;
    [ObservableProperty] private Thickness? _thicknessJuni;
    [ObservableProperty] private Thickness? _thicknessJuli;
    [ObservableProperty] private Thickness? _thicknessAugust;
    [ObservableProperty] private Thickness? _thicknessSeptember;
    [ObservableProperty] private Thickness? _thicknessOktober;
    [ObservableProperty] private Thickness? _thicknessNovember;
    [ObservableProperty] private Thickness? _thicknessDezember;

}
